[package]
name = "google_hash_code_2020"
version = "0.1.0"
authors = ["alexis <alexis.auriac@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
